// Generated by ReScript, PLEASE EDIT WITH CARE


var el = document.getElementById("CaseSectionSeparateModeAddRecordButtonButton-wrapperEl");

if (el == null) {
  console.log("Bed!");
} else {
  console.log("Good!", el);
}
